version: "3"
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "13133:13133"   # healt_check extension
      - "9411"          # Zipkin receiver
      - "4317:4317"     # OTLP receiver
    deploy:
      resources:
        limits:
          memory: 100M
    restart: unless-stopped
  