receivers:
  zipkin:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  timeout: 10s
  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  debug:
    verbosity: detailed

extensions:
  health_check:

service:
  extension: [health_check]
  pipelines:
    traces:
      receivers: [zipkin, otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]

  extensions: [zpages]